---
- name: Check if logstash-forwarder is already installed.
  stat: path=/etc/init.d/logstash-forwarder
  register: logstash_forwarder_installed

- include: install-Debian.yml
  when: logstash_forwarder_installed.stat.exists == false